apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: meeklzvm1-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/meeklzvm1-java-springboot-gitops